services:

  db:
    image: mysql:8.0.19
    environment:
      - MYSQL_DATABASE=dbUsers
      - MYSQL_ROOT_PASSWORD=db-bt-22
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - spring-mysql
    ports:
      - "3333:3306"

volumes:
  db-data: {}
networks:
  spring-mysql: {}