version: '3.7'

services:

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "databasenotas"
      MYSQL_USER: 'usr'
      MYSQL_PASSWORD: 'pwd'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    expose:
      - 3306

  mongo:
    image: mongo:4.0
    restart: always
    ports:
      - "27017:27017"
    expose:
      - 27017